---
- name: Playbook to install jenkins
  hosts: jenkins
  become: true
  gather_facts: yes
  tasks:
    - name: Install Java & other repo
      yum:
        name: ['java-1.8.0-openjdk','wget', 'git', 'curl']
        state: installed

    - name: Download jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import rpm keys
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present

    - name: Install jenkins
      yum:
        name: jenkins
        state: installed

    - name: Start & enable jenkins
      service:
        name: jenkins
        state: started
        enabled: true

    - name: Sleep for 30 seconds & continue with Play
      wait_for: timeout=30

    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Get init password for jenkins
      debug:
        var: result.stdout
    
    - name: Download maven package
      get_url:
      url: https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      dest: /opt
      mode: 0755

   - name: Extract maven package
     unarchive:
      src: /opt/apache-maven-3.6.3-bin.tar.gz
      dest: /opt
      remote_src: yes

    - name: Change permission on maven directory
      file:
       path: /opt/apache-maven-3.6.3
       owner: ansadmin
       mode: 0755
