---
- name: Playbook to install jenkins
  hosts: jenkins
  become: true
  gather_facts: yes
  tasks:
    - name: Install Java
      yum:
        name: ['java-1.8.0-openjdk','wget']
        state: installed

    - name: Download jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import rpm keys
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present

    - name: Install jenkins
      yum:
        name: jenkins
        state: installed

    - name: Start & enable jenkins
      service:
        name: jenkins
        state: started
        enabled: true

    - name: Sleep for 30 seconds & continue with Play
      wait_for: timeout=30

    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Get init password for jenkins
      debug:
        var: result.stdout
